### ISSUE TITLE
Error performing extinction predictions

### ISSUE THREAD

**Issue by JannikaO** [03rcooke/hyper_pca#1]
I have been working through the hyper_pca.Rmd file as I would like to do a similar analysis on different species for my masters dissertation. However when it comes to performing the probabilistic extinction scenarios I run into an error I cannot fix!
This is the code I am referring to (Lines 688-700 in the hyper_pca.Rmd):

```
# sample data to predict extinctions
prob_ex_m100 <- replicate(npermute, tr_ex %>% 
                            # group by IUCN category
                            dplyr::group_by(ex) %>%
                            # nest columns within dataframe
                            tidyr::nest() %>%
                            dplyr::arrange(ex) %>% 
                            # sample frac per IUCN category to probability of extinctions
                            dplyr::mutate(samp = purrr::map2(data, probs_m100, sample_frac)) %>% 
                            # select data
                            dplyr::select(ex, samp) %>% 
                            # unnest - turn data back into dataframe
                            tidyr::unnest(), simplify = FALSE)
```

I keep getting the following error and I cannot find a solution to it online. I ran the code with the data provided as well as with my own data and the error remains the same. I've also tried splitting the pipe up into smaller bits without success.

```
Error: Problem with `mutate()` column `samp`.
i `samp = purrr::map2(data, probs_m100, sample_frac)`.
i `samp` must be size 1, not 5.
i The error occurred in group 1: ex = LC.
```

Has anyone else had this issue? Is there a solution to this @03rcooke?

Thank you so much in advance for your help!
Kind regards,
JannikaO

**Comment by 03rcooke** [comment]
Hi JannikaO,

Interesting! I'm not exactly sure why that has stopped working, as it worked a few months ago when someone else used it. But maybe it's due to restructuring in `dplyr::sample_frac`. I think I've recoded it to work though, I pushed a commit to fix it, but basically I just replaced the code above with:

```r
# sample data to predict extinctions
prob_ex_m100 <- replicate(npermute, tr_ex %>% 
                            # extinction probabilities - moeers et al., 2008 
                            # 100 years into the future
                            dplyr::mutate(prob = dplyr::recode(ex, 
                                                               LC = 0.0001,
                                                               NT = 0.01,
                                                               VU = 0.1,
                                                               EN = 0.667,
                                                               CR = 0.999)) %>% 
                            # group by IUCN category
                            dplyr::group_by(ex) %>%
                            # nest columns within dataframe
                            tidyr::nest() %>%
                            # sample frac per IUCN category to probability of extinctions
                            dplyr::mutate(samp = purrr::map(data, ~sample_frac(., unique(.$prob)))) %>% 
                            # select data
                            dplyr::select(ex, samp) %>% 
                            # unnest - turn data back into dataframe
                            tidyr::unnest(cols = c(samp)), simplify = FALSE)
```

Let me know how you get on!

By the way, if you're interested in probabilistic extinction simulations we now have a more sophisticated way of modelling them, presented in this paper: Andermann, T., Faurby, S., Cooke, R., Silvestro, D. and Antonelli, A., 2021. iucn_sim: A new program to simulate future extinctions based on IUCN threat status. Ecography, 44(2), pp.162-176. https://onlinelibrary.wiley.com/doi/full/10.1111/ecog.05110

Best,
Rob

**Comment by JannikaO** [comment]
Thank you so much for the quick reply Rob! 

It works perfectly now with the new chunck of code 😄 I will let you know if I run into any other troubles further down but I think I am good to go now! 
I will definietly also check out your new way of modelling the extinction scenarios with iucn_sim. Thank you for pointing me to it.

I hope you have a wonderful day 😄 
Kind regards,
Jannika
